-- ==========================================
-- DATABASE SCHEMA - Music Rental System
-- ==========================================
-- Generated by Sequelize ORM
-- MySQL 5.7+ / MariaDB 10.3+
-- ==========================================

-- Create Database
CREATE DATABASE IF NOT EXISTS music_rental_db 
CHARACTER SET utf8mb4 
COLLATE utf8mb4_unicode_ci;

USE music_rental_db;

-- ==========================================
-- Table: users
-- ==========================================
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL UNIQUE,
  `email` VARCHAR(100) NOT NULL UNIQUE,
  `password` VARCHAR(255) NOT NULL,
  `full_name` VARCHAR(100) NOT NULL,
  `role` ENUM('admin', 'petugas', 'user') NOT NULL DEFAULT 'user',
  `phone` VARCHAR(20) NULL,
  `address` TEXT NULL,
  `is_active` BOOLEAN DEFAULT TRUE,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_username` (`username`),
  INDEX `idx_email` (`email`),
  INDEX `idx_role` (`role`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ==========================================
-- Table: categories
-- ==========================================
CREATE TABLE IF NOT EXISTS `categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL UNIQUE,
  `icon` VARCHAR(10) NOT NULL DEFAULT '🎵',
  `color` VARCHAR(7) NOT NULL DEFAULT '#6c757d',
  `description` TEXT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ==========================================
-- Table: instruments
-- ==========================================
CREATE TABLE IF NOT EXISTS `instruments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `category_id` INT NOT NULL,
  `condition` ENUM('Baik', 'Cukup', 'Rusak') NOT NULL DEFAULT 'Baik',
  `stock` INT NOT NULL DEFAULT 0,
  `price_per_day` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `description` TEXT NULL,
  `image` VARCHAR(255) NULL,
  `brand` VARCHAR(50) NULL,
  `year` INT NULL,
  `is_available` BOOLEAN DEFAULT TRUE,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  INDEX `idx_category` (`category_id`),
  INDEX `idx_name` (`name`),
  INDEX `idx_stock` (`stock`),
  INDEX `idx_available` (`is_available`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ==========================================
-- Table: rentals
-- ==========================================
CREATE TABLE IF NOT EXISTS `rentals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `instrument_id` INT NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `actual_return_date` DATE NULL,
  `status` ENUM('pending', 'approved', 'rejected', 'returned', 'cancelled') NOT NULL DEFAULT 'pending',
  `notes` TEXT NULL,
  `total_days` INT NULL,
  `total_price` DECIMAL(10,2) NULL,
  `payment_method` VARCHAR(50) DEFAULT 'cash',
  `payment_status` ENUM('pending', 'completed', 'failed') DEFAULT 'pending',
  `payment_amount` DECIMAL(10,2) DEFAULT 0.00,
  `payment_date` DATETIME NULL,
  `approved_by` INT NULL,
  `approved_at` DATETIME NULL,
  `rejection_reason` TEXT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (`instrument_id`) REFERENCES `instruments`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (`approved_by`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  INDEX `idx_user` (`user_id`),
  INDEX `idx_instrument` (`instrument_id`),
  INDEX `idx_status` (`status`),
  INDEX `idx_dates` (`start_date`, `end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ==========================================
-- SEED DATA (Default Users & Categories)
-- ==========================================

-- Insert Categories
INSERT IGNORE INTO `categories` (`id`, `name`, `icon`, `color`) VALUES
(1, 'Gitar', '🎸', '#FF6B6B'),
(2, 'Piano & Keyboard', '🎹', '#4ECDC4'),
(3, 'Drum & Perkusi', '🥁', '#FFE66D'),
(4, 'Alat Musik Tiup', '🎺', '#95E1D3'),
(5, 'Biola & String', '🎻', '#F38181'),
(6, 'Bass', '🎸', '#AA96DA'),
(7, 'Synthesizer', '🎛️', '#FCBAD3'),
(8, 'Alat Musik Tradisional', '🪘', '#A8D8EA');

-- Insert Default Users
-- admin123
INSERT IGNORE INTO `users` (`id`, `username`, `email`, `password`, `full_name`, `role`) VALUES
(1, 'admin', 'admin@music.com', '$2a$10$AfeG1hbiL8l2q4hYLfjR/eEIwHzmlFW.n/hPOrMh0lkdkaIEaO8de', 'Administrator', 'admin');

-- petugas123
INSERT IGNORE INTO `users` (`id`, `username`, `email`, `password`, `full_name`, `role`) VALUES
(2, 'petugas', 'petugas@music.com', '$2a$10$Kcxi5ora5jX8lJ12J47/7Om9inXLZIoEh9up2VNxvH01dvwy17gkW', 'Petugas Rental', 'petugas');

-- user123
INSERT IGNORE INTO `users` (`id`, `username`, `email`, `password`, `full_name`, `role`) VALUES
(3, 'user', 'user@music.com', '$2a$10$Oi57V14ulG6GZ0m11GDGwOJe/9XKEF7hYmBlsXtQwICZfyqZzidP6', 'User Demo', 'user');

-- Insert Instruments
INSERT IGNORE INTO `instruments` (`id`, `name`, `category_id`, `condition`, `stock`, `price_per_day`, `description`, `is_available`) VALUES
(1, 'Gitar Akustik Yamaha F310', 1, 'Baik', 5, 50000.00, 'Gitar akustik berkualitas tinggi dengan suara yang jernih dan balanced', 1),
(2, 'Keyboard Casio CTK-3500', 2, 'Baik', 3, 75000.00, 'Keyboard 61 keys dengan 400 tones dan 100 rhythms', 1),
(3, 'Drum Set Pearl Export', 3, 'Baik', 2, 150000.00, 'Drum set lengkap 5 piece dengan cymbal stand', 1),
(4, 'Gitar Elektrik Fender Stratocaster', 1, 'Baik', 4, 100000.00, 'Gitar elektrik legendary dengan tone yang versatile', 1),
(5, 'Bass Elektrik Ibanez SR300', 6, 'Baik', 3, 80000.00, 'Bass 4 string dengan tone yang punchy dan clear', 1),
(6, 'Saxophone Alto Yamaha YAS-280', 4, 'Baik', 2, 120000.00, 'Saxophone alto dengan suara yang warm dan responsif', 1),
(7, 'Biola 4/4 Skylark', 5, 'Baik', 4, 60000.00, 'Biola ukuran penuh dengan kualitas suara yang bagus', 1),
(8, 'Cajon Percussion', 3, 'Baik', 6, 40000.00, 'Cajon dengan snare wire untuk variasi suara', 1);

-- ==========================================
-- Sample Queries
-- ==========================================

-- Get all available instruments with category
SELECT 
  i.id,
  i.name,
  i.stock,
  i.price_per_day,
  c.name as category_name,
  c.icon,
  c.color
FROM instruments i
JOIN categories c ON i.category_id = c.id
WHERE i.is_available = TRUE AND i.stock > 0;

-- Get user's rental history
SELECT 
  r.id,
  r.status,
  r.start_date,
  r.end_date,
  r.total_price,
  i.name as instrument_name,
  i.price_per_day,
  c.name as category_name
FROM rentals r
JOIN instruments i ON r.instrument_id = i.id
JOIN categories c ON i.category_id = c.id
WHERE r.user_id = 1
ORDER BY r.created_at DESC;

-- Get pending rentals for admin
SELECT 
  r.id,
  r.start_date,
  r.end_date,
  r.notes,
  u.full_name as renter_name,
  u.email,
  i.name as instrument_name,
  i.stock
FROM rentals r
JOIN users u ON r.user_id = u.id
JOIN instruments i ON r.instrument_id = i.id
WHERE r.status = 'pending'
ORDER BY r.created_at ASC;

-- Get statistics
SELECT 
  COUNT(DISTINCT u.id) as total_users,
  COUNT(DISTINCT i.id) as total_instruments,
  COUNT(DISTINCT c.id) as total_categories,
  COUNT(r.id) as total_rentals,
  SUM(CASE WHEN r.status = 'pending' THEN 1 ELSE 0 END) as pending_rentals,
  SUM(CASE WHEN r.status = 'approved' THEN 1 ELSE 0 END) as active_rentals
FROM users u
CROSS JOIN instruments i
CROSS JOIN categories c
LEFT JOIN rentals r ON 1=1;

-- Get instruments by category with rental count
SELECT 
  c.name as category,
  c.icon,
  c.color,
  COUNT(DISTINCT i.id) as total_instruments,
  SUM(i.stock) as total_stock,
  COUNT(r.id) as total_rentals
FROM categories c
LEFT JOIN instruments i ON c.id = i.category_id
LEFT JOIN rentals r ON i.id = r.instrument_id
GROUP BY c.id
ORDER BY total_instruments DESC;

-- ==========================================
-- Useful Views (Optional)
-- ==========================================

-- View: Available Instruments
CREATE OR REPLACE VIEW v_available_instruments AS
SELECT 
  i.id,
  i.name,
  i.brand,
  i.stock,
  i.price_per_day,
  i.condition,
  i.description,
  c.name as category_name,
  c.icon as category_icon,
  c.color as category_color
FROM instruments i
JOIN categories c ON i.category_id = c.id
WHERE i.is_available = TRUE AND i.stock > 0;

-- View: Rental Details
CREATE OR REPLACE VIEW v_rental_details AS
SELECT 
  r.id,
  r.start_date,
  r.end_date,
  r.status,
  r.total_price,
  r.created_at,
  u.username as renter_username,
  u.full_name as renter_name,
  u.email as renter_email,
  u.phone as renter_phone,
  i.name as instrument_name,
  i.brand as instrument_brand,
  c.name as category_name,
  approver.full_name as approved_by_name,
  r.approved_at
FROM rentals r
JOIN users u ON r.user_id = u.id
JOIN instruments i ON r.instrument_id = i.id
JOIN categories c ON i.category_id = c.id
LEFT JOIN users approver ON r.approved_by = approver.id;

-- ==========================================
-- Backup Commands
-- ==========================================

-- Backup database
-- mysqldump -u root -p music_rental_db > backup_$(date +%Y%m%d).sql

-- Restore database
-- mysql -u root -p music_rental_db < backup_20240205.sql

-- ==========================================
-- Maintenance Queries
-- ==========================================

-- Check table sizes
SELECT 
  table_name AS 'Table',
  ROUND(((data_length + index_length) / 1024 / 1024), 2) AS 'Size (MB)'
FROM information_schema.TABLES
WHERE table_schema = 'music_rental_db'
ORDER BY (data_length + index_length) DESC;

-- Optimize tables
OPTIMIZE TABLE users, categories, instruments, rentals;

-- Check foreign key constraints
SELECT 
  CONSTRAINT_NAME,
  TABLE_NAME,
  COLUMN_NAME,
  REFERENCED_TABLE_NAME,
  REFERENCED_COLUMN_NAME
FROM information_schema.KEY_COLUMN_USAGE
WHERE REFERENCED_TABLE_SCHEMA = 'music_rental_db';