-- ==========================================
-- DATABASE SCHEMA - Music Rental System
-- ==========================================
-- Generated by Sequelize ORM
-- MySQL 5.7+ / MariaDB 10.3+
-- ==========================================

-- Create Database
CREATE DATABASE IF NOT EXISTS music_rental_db 
CHARACTER SET utf8mb4 
COLLATE utf8mb4_unicode_ci;

USE music_rental_db;

-- ==========================================
-- Table: users
-- ==========================================
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL UNIQUE,
  `email` VARCHAR(100) NOT NULL UNIQUE,
  `password` VARCHAR(255) NOT NULL,
  `full_name` VARCHAR(100) NOT NULL,
  `role` ENUM('admin', 'petugas', 'user') NOT NULL DEFAULT 'user',
  `phone` VARCHAR(20) NULL,
  `address` TEXT NULL,
  `is_active` BOOLEAN DEFAULT TRUE,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_username` (`username`),
  INDEX `idx_email` (`email`),
  INDEX `idx_role` (`role`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ==========================================
-- Table: categories
-- ==========================================
CREATE TABLE IF NOT EXISTS `categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL UNIQUE,
  `icon` VARCHAR(10) NOT NULL DEFAULT '🎵',
  `color` VARCHAR(7) NOT NULL DEFAULT '#6c757d',
  `description` TEXT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ==========================================
-- Table: instruments
-- ==========================================
CREATE TABLE IF NOT EXISTS `instruments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `category_id` INT NOT NULL,
  `condition` ENUM('Baik', 'Cukup', 'Rusak') NOT NULL DEFAULT 'Baik',
  `stock` INT NOT NULL DEFAULT 0,
  `price_per_day` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `description` TEXT NULL,
  `image` VARCHAR(255) NULL,
  `brand` VARCHAR(50) NULL,
  `year` INT NULL,
  `is_available` BOOLEAN DEFAULT TRUE,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  INDEX `idx_category` (`category_id`),
  INDEX `idx_name` (`name`),
  INDEX `idx_stock` (`stock`),
  INDEX `idx_available` (`is_available`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ==========================================
-- Table: rentals
-- ==========================================
CREATE TABLE IF NOT EXISTS `rentals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `instrument_id` INT NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `actual_return_date` DATE NULL,
  `status` ENUM('pending', 'approved', 'rejected', 'returned', 'cancelled') NOT NULL DEFAULT 'pending',
  `notes` TEXT NULL,
  `total_days` INT NULL,
  `total_price` DECIMAL(10,2) NULL,
  `payment_method` VARCHAR(50) DEFAULT 'cash',
  `payment_status` ENUM('pending', 'completed', 'failed') DEFAULT 'pending',
  `payment_amount` DECIMAL(10,2) DEFAULT 0.00,
  `payment_date` DATETIME NULL,
  `approved_by` INT NULL,
  `approved_at` DATETIME NULL,
  `rejection_reason` TEXT NULL,
  `late_fee_per_day` DECIMAL(10,2) DEFAULT 0.00,
  `late_days` INT DEFAULT 0,
  `late_fee_total` DECIMAL(10,2) DEFAULT 0.00,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (`instrument_id`) REFERENCES `instruments`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (`approved_by`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  INDEX `idx_user` (`user_id`),
  INDEX `idx_instrument` (`instrument_id`),
  INDEX `idx_status` (`status`),
  INDEX `idx_dates` (`start_date`, `end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ==========================================
-- SEED DATA (Default Users & Categories)
-- ==========================================

-- Insert Categories
INSERT IGNORE INTO `categories` (`id`, `name`, `icon`, `color`) VALUES
(1, 'Gitar', '🎸', '#FF6B6B'),
(2, 'Piano & Keyboard', '🎹', '#4ECDC4'),
(3, 'Drum & Perkusi', '🥁', '#FFE66D'),
(4, 'Alat Musik Tiup', '🎺', '#95E1D3'),
(5, 'Biola & String', '🎻', '#F38181'),
(6, 'Bass', '🎸', '#AA96DA'),
(7, 'Synthesizer', '🎛️', '#FCBAD3'),
(8, 'Alat Musik Tradisional', '🪘', '#A8D8EA');

-- Insert Default Users
-- admin123
INSERT IGNORE INTO `users` (`id`, `username`, `email`, `password`, `full_name`, `role`) VALUES
(1, 'admin', 'admin@music.com', '$2a$10$AfeG1hbiL8l2q4hYLfjR/eEIwHzmlFW.n/hPOrMh0lkdkaIEaO8de', 'Administrator', 'admin');

-- petugas123
INSERT IGNORE INTO `users` (`id`, `username`, `email`, `password`, `full_name`, `role`) VALUES
(2, 'petugas', 'petugas@music.com', '$2a$10$Kcxi5ora5jX8lJ12J47/7Om9inXLZIoEh9up2VNxvH01dvwy17gkW', 'Petugas Rental', 'petugas');

-- user123
INSERT IGNORE INTO `users` (`id`, `username`, `email`, `password`, `full_name`, `role`) VALUES
(3, 'user', 'user@music.com', '$2a$10$Oi57V14ulG6GZ0m11GDGwOJe/9XKEF7hYmBlsXtQwICZfyqZzidP6', 'User Demo', 'user');

-- Insert Instruments (15 items per category)
INSERT IGNORE INTO `instruments` (`id`, `name`, `category_id`, `condition`, `stock`, `price_per_day`, `description`, `is_available`) VALUES
-- Category 1: Gitar (Guitar)
(1, 'Gitar Akustik Yamaha F310', 1, 'Baik', 5, 50000.00, 'Gitar akustik berkualitas tinggi dengan suara yang jernih dan balanced', 1),
(4, 'Gitar Elektrik Fender Stratocaster', 1, 'Baik', 4, 100000.00, 'Gitar elektrik legendary dengan tone yang versatile', 1),
(9, 'Gitar Akustik Squier SA-150', 1, 'Baik', 3, 45000.00, 'Gitar akustik entry level dengan kualitas suara yang baik', 1),
(10, 'Gitar Elektrik Gibson Les Paul', 1, 'Baik', 2, 180000.00, 'Gitar elektrik premium dengan tone yang kaya dan warm', 1),
(11, 'Gitar Akustik Takamine GD30', 1, 'Baik', 4, 85000.00, 'Gitar akustik dengan sistem elektrik built-in', 1),
(12, 'Gitar Elektrik Epiphone SG Special', 1, 'Baik', 3, 95000.00, 'Gitar elektrik dengan design yang iconic', 1),
(13, 'Gitar Akustik Ibanez Acoustic', 1, 'Baik', 3, 65000.00, 'Gitar akustik dengan neck yang comfortable', 1),
(14, 'Gitar Elektrik Jackson JS Series', 1, 'Baik', 2, 75000.00, 'Gitar elektrik dengan design modern dan agresif', 1),
(15, 'Gitar Akustik Cort AD810', 1, 'Baik', 4, 60000.00, 'Gitar akustik dengan tone yang resonan', 1),
(16, 'Gitar Elektrik PRS SE Custom 24', 1, 'Baik', 2, 130000.00, 'Gitar elektrik dengan craftsmanship superior', 1),
(17, 'Gitar Semi-Akustik Ibanez AS73', 1, 'Baik', 3, 110000.00, 'Gitar semi-akustik dengan body yang hollow', 1),
(18, 'Gitar Akustik Ovation Celebrity', 1, 'Baik', 2, 95000.00, 'Gitar akustik dengan bowl-back design yang unik', 1),
(19, 'Gitar Elektrik Schecter Diamond', 1, 'Baik', 2, 115000.00, 'Gitar elektrik dengan pickup yang powerful', 1),
(20, 'Gitar Akustik Martin D-28', 1, 'Baik', 1, 250000.00, 'Gitar akustik premium dengan suara yang legendary', 1),
(21, 'Gitar Elektrik Fender Jazzmaster', 1, 'Baik', 2, 105000.00, 'Gitar elektrik dengan tone yang smooth dan jazzy', 1),

-- Category 2: Piano & Keyboard
(2, 'Keyboard Casio CTK-3500', 2, 'Baik', 3, 75000.00, 'Keyboard 61 keys dengan 400 tones dan 100 rhythms', 1),
(22, 'Keyboard Yamaha PSR-E473', 2, 'Baik', 3, 80000.00, 'Keyboard dengan suara yang realistic dan built-in sequencer', 1),
(23, 'Keyboard Roland E-X20', 2, 'Baik', 2, 120000.00, 'Keyboard performance dengan sound quality yang excellent', 1),
(24, 'Piano Digital Yamaha P-125', 2, 'Baik', 2, 150000.00, 'Piano digital portable dengan 88 weighted keys', 1),
(25, 'Piano Digital Casio PX-870', 2, 'Baik', 2, 180000.00, 'Piano digital stage quality dengan dual speaker system', 1),
(26, 'Keyboard Korg Kross 2', 2, 'Baik', 1, 200000.00, 'Keyboard synthesizer profesional dengan 88 keys', 1),
(27, 'Keyboard Roland Juno-DS', 2, 'Baik', 2, 140000.00, 'Keyboard dengan sound synth yang versatile', 1),
(28, 'Piano Digital Nord Electro', 2, 'Baik', 1, 250000.00, 'Piano digital dengan teknologi Nord terkini', 1),
(29, 'Keyboard Behringer UMX610', 2, 'Baik', 3, 50000.00, 'Keyboard controller dengan 49 keys dan USB interface', 1),
(30, 'Piano Digital Kurzweil Mark One', 2, 'Baik', 1, 220000.00, 'Piano digital dengan 88 weighted hammer action keys', 1),
(31, 'Keyboard Moog Sub Phatty', 2, 'Baik', 1, 190000.00, 'Synthesizer analog compact dengan 25 keys', 1),
(32, 'Synthesizer Keyboard Nord Lead', 2, 'Baik', 1, 280000.00, 'Synthesizer digital dengan sound polyphonic', 1),
(33, 'Piano Digital Roland FP-90X', 2, 'Baik', 1, 210000.00, 'Piano stage profesional dengan 88 keys Ivory weighted', 1),
(34, 'Keyboard Electone Yamaha', 2, 'Baik', 1, 300000.00, 'Keyboard electone klasik Indonesia dengan pedal', 1),
(35, 'Piano Digital Kawai MP6', 2, 'Baik', 1, 230000.00, 'Piano digital dengan responsiveness yang tinggi', 1),

-- Category 3: Drum & Perkusi (Drums & Percussion)
(3, 'Drum Set Pearl Export', 3, 'Baik', 2, 150000.00, 'Drum set lengkap 5 piece dengan cymbal stand', 1),
(8, 'Cajon Percussion', 3, 'Baik', 6, 40000.00, 'Cajon dengan snare wire untuk variasi suara', 1),
(36, 'Drum Set Ludwig Classic', 3, 'Baik', 1, 200000.00, 'Drum set classik dengan hardware berkualitas tinggi', 1),
(37, 'Drum Set Gretsch USA Custom', 3, 'Baik', 1, 250000.00, 'Drum set USA dengan sound yang warm dan vintage', 1),
(38, 'Drum Set Tama Starclassic', 3, 'Baik', 2, 180000.00, 'Drum set dengan shells yang berkualitas profesional', 1),
(39, 'Cajon Meinl Walnut', 3, 'Baik', 4, 60000.00, 'Cajon dengan material walnut yang resonan', 1),
(40, 'Drum Set DW Design Series', 3, 'Baik', 1, 220000.00, 'Drum set dengan design yang modern dan sophisticated', 1),
(41, 'Timpani Yamaha Concert', 3, 'Baik', 1, 280000.00, 'Timpani dengan sistem tuning yang presisi', 1),
(42, 'Xylophone Majestic', 3, 'Baik', 2, 100000.00, 'Xylophone 3.5 octave dengan resonators', 1),
(43, 'Vibraphone Musser M-55', 3, 'Baik', 1, 350000.00, 'Vibraphone profesional dengan motor yang smooth', 1),
(44, 'Drum Set Sonor AQX Series', 3, 'Baik', 1, 170000.00, 'Drum set dengan coating warna yang custom', 1),
(45, 'Frame Drum Bodhran', 3, 'Baik', 3, 45000.00, 'Frame drum dengan sound yang authentic Celtic', 1),
(46, 'Conga Meinl Artist Series', 3, 'Baik', 2, 140000.00, 'Conga dengan tuning yang responsive', 1),
(47, 'Bongos Tunable Remo', 3, 'Baik', 3, 55000.00, 'Bongos dengan tuning head yang adjustable', 1),
(48, 'Steel Drum Caribbean', 3, 'Baik', 1, 400000.00, 'Steel drum dengan tone yang bright dan melodis', 1),

-- Category 4: Alat Musik Tiup (Wind Instruments)
(6, 'Saxophone Alto Yamaha YAS-280', 4, 'Baik', 2, 120000.00, 'Saxophone alto dengan suara yang warm dan responsif', 1),
(49, 'Flute Yamaha YFL-212', 4, 'Baik', 3, 65000.00, 'Flute dengan mechanism yang smooth', 1),
(50, 'Trumpet Bach LT190S', 4, 'Baik', 2, 95000.00, 'Trumpet dengan suara yang bright dan projeksi yang bagus', 1),
(51, 'Saxophone Tenor Selmer TS111', 4, 'Baik', 1, 180000.00, 'Saxophone tenor dengan tone yang deep dan rich', 1),
(52, 'Clarinet Buffet Crampon R13', 4, 'Baik', 2, 110000.00, 'Clarinet profesional dengan response yang cepat', 1),
(53, 'Trombone Yamaha YSL-354', 4, 'Baik', 2, 130000.00, 'Trombone tenor dengan sound quality yang excellent', 1),
(54, 'French Horn Yamaha YHR-567', 4, 'Baik', 1, 150000.00, 'French horn dengan tuning yang stabil', 1),
(55, 'Oboe Lowell Classical', 4, 'Baik', 1, 140000.00, 'Oboe dengan tone yang mellow dan expressive', 1),
(56, 'Saxophone Soprano Selmer USA', 4, 'Baik', 1, 200000.00, 'Saxophone soprano dengan sound yang penetrating', 1),
(57, 'Flute Gemeinhardt M2', 4, 'Baik', 2, 70000.00, 'Flute concert dengan material yang berkualitas', 1),
(58, 'Trumpet Getzen Eterna', 4, 'Baik', 1, 120000.00, 'Trumpet dengan valve yang responsive', 1),
(59, 'Clarinet Leblanc L7', 4, 'Baik', 1, 100000.00, 'Clarinet dengan intonation yang akurat', 1),
(60, 'Trombone Bach 42AF', 4, 'Baik', 1, 180000.00, 'Trombone profesional dengan slide yang smooth', 1),
(61, 'Piccolo Armstrong', 4, 'Baik', 1, 50000.00, 'Piccolo dengan tone yang clear dan brilliant', 1),
(62, 'Bassoon Heckel', 4, 'Baik', 1, 280000.00, 'Bassoon profesional dengan sound yang complex dan warm', 1),

-- Category 5: Biola & String (Violin & String)
(7, 'Biola 4/4 Skylark', 5, 'Baik', 4, 60000.00, 'Biola ukuran penuh dengan kualitas suara yang bagus', 1),
(63, 'Biola 4/4 Stentor Student II', 5, 'Baik', 3, 45000.00, 'Biola student grade dengan material yang solid', 1),
(64, 'Cello Yamaha SVC210', 5, 'Baik', 1, 180000.00, 'Cello dengan tone yang resonan dan projections yang bagus', 1),
(65, 'Biola 4/4 Strunal', 5, 'Baik', 2, 55000.00, 'Biola dengan setup yang profesional', 1),
(66, 'Mandolin Fender FM-52E', 5, 'Baik', 2, 75000.00, 'Mandolin dengan suara yang bright dan punchy', 1),
(67, 'Ukulele Kala KA-15F', 5, 'Baik', 4, 35000.00, 'Ukulele soprano dengan suara yang warm', 1),
(68, 'Biola 3/4 Cecilio', 5, 'Baik', 2, 50000.00, 'Biola 3/4 ukuran untuk pemula hingga intermediate', 1),
(69, 'Cello Yamaha SVC50', 5, 'Baik', 1, 150000.00, 'Cello dengan sound yang mellow dan full-bodied', 1),
(70, 'Banjo 5-String Deering Artisan', 5, 'Baik', 1, 160000.00, 'Banjo dengan tone yang bright dan cutting', 1),
(71, 'Sitar Ravi Shankar', 5, 'Baik', 1, 220000.00, 'Sitar klasik dengan resonator yang premium', 1),
(72, 'Balalaika Russian', 5, 'Baik', 1, 85000.00, 'Balalaika dengan sound yang distinctive', 1),
(73, 'Tamboura Classical', 5, 'Baik', 1, 120000.00, 'Tamboura dengan strings yang harmonis', 1),
(74, 'Oud Nay Gazheli', 5, 'Baik', 1, 140000.00, 'Oud dengan tone yang deep dan mystical', 1),
(75, 'Lute Renaissance Style', 5, 'Baik', 1, 110000.00, 'Lute dengan design yang historical', 1),
(76, 'Hurdy Gurdy Musician', 5, 'Baik', 1, 450000.00, 'Hurdy gurdy dengan sound yang unik dan ethnic', 1),

-- Category 6: Bass
(5, 'Bass Elektrik Ibanez SR300', 6, 'Baik', 3, 80000.00, 'Bass 4 string dengan tone yang punchy dan clear', 1),
(77, 'Bass Akustik Yamaha BB1024', 6, 'Baik', 1, 120000.00, 'Bass akustik dengan resonansi yang dalam', 1),
(78, 'Bass Fender Precision', 6, 'Baik', 2, 140000.00, 'Bass legendary dengan tone yang fat dan solid', 1),
(79, 'Bass Ibanez Soundgear', 6, 'Baik', 2, 100000.00, 'Bass dengan body yang ergonomis dan confortable', 1),
(80, 'Bass Warwick Corvette', 6, 'Baik', 1, 160000.00, 'Bass premium dengan craftsmanship Jerman', 1),
(81, 'Bass Schecter Stiletto', 6, 'Baik', 1, 130000.00, 'Bass dengan design yang aggressive dan modern', 1),
(82, 'Bass Spector Euro', 6, 'Baik', 1, 150000.00, 'Bass dengan tone yang thick dan powerful', 1),
(83, 'Bass Fender Jazz Bass', 6, 'Baik', 1, 135000.00, 'Bass jazz classic dengan tone yang versatile', 1),
(84, 'Bass Music Man StingRay', 6, 'Baik', 1, 180000.00, 'Bass dengan pickup yang dapat di-switch', 1),
(85, 'Bass PRS Mira', 6, 'Baik', 1, 170000.00, 'Bass dengan tone yang balanced dan smooth', 1),
(86, 'Bass Fodera Monarch 4', 6, 'Baik', 1, 280000.00, 'Bass handmade premium dengan suara yang exceptional', 1),
(87, 'Bass Dingwall Genesis', 6, 'Baik', 1, 200000.00, 'Bass dengan 40mm nut yang lebar', 1),
(88, 'Bass Modulus Modules 4', 6, 'Baik', 1, 190000.00, 'Bass dengan graphite neck yang stable', 1),
(89, 'Bass G&L L2000', 6, 'Baik', 1, 155000.00, 'Bass dengan MFD pickup yang versatile', 1),
(90, 'Bass Ernie Ball Music Man', 6, 'Baik', 1, 175000.00, 'Bass dengan suara yang bright dan articulate', 1),

-- Category 7: Synthesizer
(91, 'Synthesizer Nord Lead A1', 7, 'Baik', 1, 280000.00, 'Synthesizer digital dengan polyphonic sound', 1),
(92, 'Moog One 8 Voice', 7, 'Baik', 1, 320000.00, 'Synthesizer analog dengan 8 oscillators', 1),
(93, 'Sequential Prophet Rev2', 7, 'Baik', 1, 300000.00, 'Synthesizer dengan 16 voice polyphony', 1),
(94, 'Dave Smith؛ Prophet-6', 7, 'Baik', 1, 310000.00, 'Synthesizer 6 voice dengan analog sound', 1),
(95, 'Korg Prologue', 7, 'Baik', 1, 250000.00, 'Synthesizer hybrid dengan synth engine yang powerful', 1),
(96, 'Yamaha DX7 Original', 7, 'Baik', 1, 200000.00, 'Synthesizer FM legendary dengan sound yang iconic', 1),
(97, 'Minimoog Voyager', 7, 'Baik', 1, 290000.00, 'Synthesizer monophonic analog dengan 3 oscillators', 1),
(98, 'Elektron Analog Keys', 7, 'Baik', 1, 270000.00, 'Synthesizer dengan sequencer dan sampler', 1),
(99, 'Arturia Prophet V2', 7, 'Baik', 1, 260000.00, 'Synthesizer virtual analog dengan 16 voice', 1),
(100, 'Teenage Engineering OP-1', 7, 'Baik', 1, 240000.00, 'Synthesizer portable dengan built-in tape synth', 1),
(101, 'Moog Moogerfooger', 7, 'Baik', 2, 80000.00, 'Synthesizer pedal effects dengan analog circuitry', 1),
(102, 'Korg Monotron', 7, 'Baik', 1, 100000.00, 'Synthesizer monophonic portable dengan ribbon keyboard', 1),
(103, 'Clavia Nord Modular G2', 7, 'Baik', 1, 310000.00, 'Synthesizer modular virtual dengan 150 modules', 1),
(104, 'Waldorf Q', 7, 'Baik', 1, 280000.00, 'Synthesizer dengan wavetable engine yang sophisticated', 1),
(105, 'Alesis Ion', 7, 'Baik', 1, 150000.00, 'Synthesizer workstation dengan 49 weighted keys', 1),

-- Category 8: Alat Musik Tradisional (Traditional Instruments)
(106, 'Gamelan Jawa Sleman', 8, 'Baik', 1, 300000.00, 'Set gamelan lengkap dengan 12 instrumen', 1),
(107, 'Rebab Klasik', 8, 'Baik', 2, 65000.00, 'Rebab dengan suara yang dalam dan misterius', 1),
(108, 'Suling Bambu Sundanese', 8, 'Baik', 3, 40000.00, 'Suling tradisional dengan tone yang warm', 1),
(109, 'Angklung Bamboo Set', 8, 'Baik', 2, 55000.00, 'Set angklung lengkap untuk 10 pemain', 1),
(110, 'Kendang Ciblon', 8, 'Baik', 3, 45000.00, 'Kendang tradisional dengan sound yang khas', 1),
(111, 'Talempong Minangkabau', 8, 'Baik', 1, 70000.00, 'Talempong set dengan 5 instrumen', 1),
(112, 'Seruling Palembang', 8, 'Baik', 2, 35000.00, 'Seruling tradisional dengan tuning yang traditional', 1),
(113, 'Tifa Papua', 8, 'Baik', 1, 85000.00, 'Tifa dengan ukiran tradisional yang unik', 1),
(114, 'Kolintang Minahasan', 8, 'Baik', 1, 120000.00, 'Kolintang dengan 25 keys dari kayu pilihan', 1),
(115, 'Gendang Bujang', 8, 'Baik', 2, 50000.00, 'Gendang tradisional Melayu dengan sound penuh', 1),
(116, 'Gambus Arab', 8, 'Baik', 1, 140000.00, 'Gambus dengan 8 double strings', 1),
(117, 'Tabla Indian', 8, 'Baik', 2, 80000.00, 'Tabla pair dengan tuning yang profesional', 1),
(118, 'Gong Javanese', 8, 'Baik', 1, 250000.00, 'Gong dengan diameter 60cm yang resonan', 1),
(119, 'Calung Sundanese', 8, 'Baik', 1, 100000.00, 'Calung tradisional dengan 13 bamboo pieces', 1),
(120, 'Bonang Pelog', 8, 'Baik', 1, 180000.00, 'Bonang dengan 10 gongs dalam nada Pelog', 1);

-- ==========================================
-- Sample Queries
-- ==========================================

-- Get all available instruments with category
SELECT 
  i.id,
  i.name,
  i.stock,
  i.price_per_day,
  c.name as category_name,
  c.icon,
  c.color
FROM instruments i
JOIN categories c ON i.category_id = c.id
WHERE i.is_available = TRUE AND i.stock > 0;

-- Get user's rental history
SELECT 
  r.id,
  r.status,
  r.start_date,
  r.end_date,
  r.total_price,
  i.name as instrument_name,
  i.price_per_day,
  c.name as category_name
FROM rentals r
JOIN instruments i ON r.instrument_id = i.id
JOIN categories c ON i.category_id = c.id
WHERE r.user_id = 1
ORDER BY r.created_at DESC;

-- Get pending rentals for admin
SELECT 
  r.id,
  r.start_date,
  r.end_date,
  r.notes,
  u.full_name as renter_name,
  u.email,
  i.name as instrument_name,
  i.stock
FROM rentals r
JOIN users u ON r.user_id = u.id
JOIN instruments i ON r.instrument_id = i.id
WHERE r.status = 'pending'
ORDER BY r.created_at ASC;

-- Get statistics
SELECT 
  COUNT(DISTINCT u.id) as total_users,
  COUNT(DISTINCT i.id) as total_instruments,
  COUNT(DISTINCT c.id) as total_categories,
  COUNT(r.id) as total_rentals,
  SUM(CASE WHEN r.status = 'pending' THEN 1 ELSE 0 END) as pending_rentals,
  SUM(CASE WHEN r.status = 'approved' THEN 1 ELSE 0 END) as active_rentals
FROM users u
CROSS JOIN instruments i
CROSS JOIN categories c
LEFT JOIN rentals r ON 1=1;

-- Get instruments by category with rental count
SELECT 
  c.name as category,
  c.icon,
  c.color,
  COUNT(DISTINCT i.id) as total_instruments,
  SUM(i.stock) as total_stock,
  COUNT(r.id) as total_rentals
FROM categories c
LEFT JOIN instruments i ON c.id = i.category_id
LEFT JOIN rentals r ON i.id = r.instrument_id
GROUP BY c.id
ORDER BY total_instruments DESC;

-- ==========================================
-- Useful Views (Optional)
-- ==========================================

-- View: Available Instruments
CREATE OR REPLACE VIEW v_available_instruments AS
SELECT 
  i.id,
  i.name,
  i.brand,
  i.stock,
  i.price_per_day,
  i.condition,
  i.description,
  c.name as category_name,
  c.icon as category_icon,
  c.color as category_color
FROM instruments i
JOIN categories c ON i.category_id = c.id
WHERE i.is_available = TRUE AND i.stock > 0;

-- View: Rental Details
CREATE OR REPLACE VIEW v_rental_details AS
SELECT 
  r.id,
  r.start_date,
  r.end_date,
  r.status,
  r.total_price,
  r.created_at,
  u.username as renter_username,
  u.full_name as renter_name,
  u.email as renter_email,
  u.phone as renter_phone,
  i.name as instrument_name,
  i.brand as instrument_brand,
  c.name as category_name,
  approver.full_name as approved_by_name,
  r.approved_at
FROM rentals r
JOIN users u ON r.user_id = u.id
JOIN instruments i ON r.instrument_id = i.id
JOIN categories c ON i.category_id = c.id
LEFT JOIN users approver ON r.approved_by = approver.id;

-- ==========================================
-- Backup Commands
-- ==========================================

-- Backup database
-- mysqldump -u root -p music_rental_db > backup_$(date +%Y%m%d).sql

-- Restore database
-- mysql -u root -p music_rental_db < backup_20240205.sql

-- ==========================================
-- Maintenance Queries
-- ==========================================

-- Check table sizes
SELECT 
  table_name AS 'Table',
  ROUND(((data_length + index_length) / 1024 / 1024), 2) AS 'Size (MB)'
FROM information_schema.TABLES
WHERE table_schema = 'music_rental_db'
ORDER BY (data_length + index_length) DESC;

-- Optimize tables
OPTIMIZE TABLE users, categories, instruments, rentals;

-- Check foreign key constraints
SELECT 
  CONSTRAINT_NAME,
  TABLE_NAME,
  COLUMN_NAME,
  REFERENCED_TABLE_NAME,
  REFERENCED_COLUMN_NAME
FROM information_schema.KEY_COLUMN_USAGE
WHERE REFERENCED_TABLE_SCHEMA = 'music_rental_db';